#!/bin/bash
set -e

psql \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  -v ON_ERROR_STOP=1 <<SQL

CREATE ROLE "$POSTGRES_READONLY_USER"
    LOGIN
    PASSWORD '${POSTGRES_READONLY_PASSWORD}';

GRANT CONNECT ON DATABASE "$POSTGRES_DB"
    TO "$POSTGRES_READONLY_USER";

GRANT USAGE ON SCHEMA raw, staging, mart
    TO "$POSTGRES_READONLY_USER";

GRANT SELECT ON ALL TABLES IN SCHEMA raw, staging, mart
    TO "$POSTGRES_READONLY_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER"
    IN SCHEMA raw, staging, mart
    GRANT SELECT ON TABLES TO "$POSTGRES_READONLY_USER";

SQL