fintech_warehouse:
  target: dev

  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: fintech
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: fintech
      schema: staging
      threads: 4
